version: '3.9'

services:
  redis:
    image: redis:7
    container_name: loans-redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: